package main

import (
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"blindvault/pkg/crypto"
)

const (
	masterSeedHex   = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
	epoch           = "2026-01"
	credentialClass = "tier_gold"
	message         = "Hello BlindVault"
	dst             = "BCIS-V1-MESSAGE"
)

func main() {
	outputPath := flag.String("output", "docs/crypto_vectors.md", "path to write generated test vectors")
	flag.Parse()

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create output directory: %v\n", err)
		os.Exit(1)
	}

	f, err := os.Create(*outputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to create output file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	seed, err := hex.DecodeString(masterSeedHex)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to decode master seed: %v\n", err)
		os.Exit(1)
	}

	engine := crypto.NewBLS12Engine()

	sk, err := crypto.DeriveSigningKey(seed, epoch, credentialClass)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to derive signing key: %v\n", err)
		os.Exit(1)
	}

	pk := sk.PubKey()

	msgPoint, err := engine.HashToCurve([]byte(message), []byte(dst))
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to hash to curve: %v\n", err)
		os.Exit(1)
	}

	r, err := crypto.NewRandomScalar()
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to generate blinding scalar: %v\n", err)
		os.Exit(1)
	}

	blinded, err := engine.BlindMessage(msgPoint, r)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to blind message: %v\n", err)
		os.Exit(1)
	}

	blindSig, err := engine.SignBlinded(blinded, sk)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to sign blinded message: %v\n", err)
		os.Exit(1)
	}

	unblinded, err := engine.UnblindSignature(blindSig, r)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to unblind signature: %v\n", err)
		os.Exit(1)
	}

	witness := msgPoint
	nullifier := crypto.ComputeNullifier(epoch, credentialClass, unblinded)

	proof, err := engine.DLEQProve(sk, blinded, pk)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to generate DLEQ proof: %v\n", err)
		os.Exit(1)
	}

	if !engine.DLEQVerify(proof, blinded, blindSig, pk) {
		fmt.Fprintln(os.Stderr, "DLEQ proof verification failed")
		os.Exit(1)
	}
	SK := sk.Bytes()
	s := proof.S.Bytes()
	c := proof.C.Bytes()
	_, err = fmt.Fprintf(f, `# Generated Crypto Test Vectors

> Generated by `+"scripts/generate_vectors.go"+`.
>
> Run: `+"go run scripts/generate_vectors.go --output docs/crypto_vectors.md"+`
>

## Parameters

- master_seed_hex: "%s"
- epoch: "%s"
- credential_class: "%s"
- message: "%s"
- dst: "%s"

## Derived Keys

- derived_sk: "%s"
- public_key: "%s"

## Issuance

- blinded_message: "%s"
- blind_signature: "%s"
- proof_r1: "%s"
- proof_r2: "%s"
- proof_s: "%s"
- proof_c: "%s"

## Consumption

- unblinded_signature: "%s"
- witness: "%s"
- nullifier: "%s"
`,
		masterSeedHex,
		epoch,
		credentialClass,
		message,
		dst,
		hex.EncodeToString(SK[:]),
		hex.EncodeToString(pk.Compress()),
		hex.EncodeToString(blinded.Compress()),
		hex.EncodeToString(blindSig.Compress()),
		hex.EncodeToString(proof.R1.Compress()),
		hex.EncodeToString(proof.R2.Compress()),
		hex.EncodeToString(s[:]),
		hex.EncodeToString(c[:]),
		hex.EncodeToString(unblinded.Compress()),
		hex.EncodeToString(witness.Compress()),
		hex.EncodeToString(nullifier),
	)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to write vectors: %v\n", err)
		os.Exit(1)
	}
}
